version: "3.8"

services:
  prisma_deliveries:
    image: postgres
    container_name: prisma_deliveries
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=prisma_deliveries
    volumes:
      - pgdata:/data/postgres
volumes:
  pgdata:
    driver: local
